apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - image: mylocalregistry.azurecr.io/vehicledocker:latest
        name: myapp
        ports:
        - containerPort: 80
          name: myapp        