on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: yashwanthkumar1999/demo:latest
      - name: Deploy to VM
        uses: appleboy/ssh-action@master
        with:
         host: 40.127.203.186
         username: demo
         password: ${{ secrets.VM_PASSWORD }} 
         port: 22
         script: |
          # Commands to execute on the VM after SSH connection
          sudo docker stop my-container || true
          sudo docker rm my-container || true
          sudo docker run -d --name my-container -p 8080:5000 yashwanthkumar1999/demo:latest


  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to AKS
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: AKS-rg
          cluster-name: demo
        id: login

     # - name: Configure deployment
      #  uses: azure/k8s-bake@v1
       ##  renderEngine: 'helm'
         # helmChart: MY_HELM_FILE              # Replace with the path to your Helm chart
          #overrideFiles: MY_OVERRIDE_FILES     # Replace with the path to your Helm override files (if any)
          #overrides: |
         #   replicas: 2
          #helm-version: 'latest'
        #id: bake

      - name: Deploy application
        uses: azure/k8s-deploy@v1
        with:
          manifests: |
            app.yml
            service.yml
          #images: |
           # yashwanthkumar1999/demo:latest 
